version: "3.8"
name: cmpt371-group2
services:
  app:
    container_name: covid_app
    hostname: covid_app
    image: sask-long-covid-app
    build:
      context: ./app
      dockerfile: .docker/dev.Dockerfile
    volumes:
      - ./app:/app
      - app_node_modules:/app/node_modules
    working_dir: /app
    ports:
      - 3080:3080
    tty: true
    stdin_open: true
    restart: unless-stopped
    depends_on:
      - covid_api

  api:
    container_name: covid_api
    hostname: covid_api
    image: sask-long-covid-api
    build:
      context: ./api
      dockerfile: .docker/dev.Dockerfile
    volumes:
      - ./api:/app
      - api_node_modules:/app/node_modules
    working_dir: /app
    ports:
      - 8080:8080
    tty: true
    stdin_open: true
    restart: unless-stopped
    env_file:
      - db/.env
      - api/env/development.env


  postgres:
    image: postgres:15.1-alpine3.17
    hostname: covid_postgres
    container_name: covid_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - SaskLongCovidDevData:/var/lib/postgresql/data
    env_file:
      - ./db/.env
      
volumes:
  app_node_modules:
  api_node_modules:
  SaskLongCovidDevData: