import React from 'react';
import DataTable from './DataTable';
import CovidTable from './CovidTable';
import SymptomTable from './SymptomTable';

function Table() {
  const data1 = {
    Name: 42176,
    'Device ID': '85FF7229C0BB4514890B9AAF86DF4CAE',
    'Scheduled Time': '2022-02-03 21:50:35 MST',
    'Issued Time': '2022-02-03 21:50:35 MST',
    'Response Time': '2022-02-04 09:16:52 MST',
    'Duration (seconds) from scheduled to completion time': 41177.533,
    'Duration (seconds) from first response to completion time': 1427,
  };

  const data2 = {
    Name: 12345,
    'Device ID': 'A1B2C3D4E5F6G7H8',
    'Scheduled Time': '2022-02-03 21:50:35 MST',
    'Issued Time': '2022-02-03 21:50:35 MST',
    'Response Time': '2022-02-04 09:16:52 MST',
    'Duration (seconds) from scheduled to completion time': 1234.567,
    'Duration (seconds) from first response to completion time': 5678,
  };

  const dataArray = [
    {
      Name: 42176,
      'Device ID': '85FF7229C0BB4514890B9AAF86DF4CAE',
      'Scheduled Time': '2022-02-03 21:50:35 MST',
      'Issued Time': '2022-02-03 21:50:35 MST',
      'Response Time': '2022-02-04 09:16:52 MST',
      'Duration (seconds) from scheduled to completion time': 41177.533,
      'Duration (seconds) from first response to completion time': 1427,
      Location: 'Unknown',
      '[156_SAQ] Have you had COVID-19? This can be medically confi': 2,
      '[1_SAQ] Were you confirmed positive for COVID-19 by either': 2,
      '[2_SAQ] How long ago were you confirmed to have or suspect': 5,
      '[4_SAQ] How severe in your opinion was the disease within ': 1,
      '[157_MAQ_5] Never told that I experienced these things': 'true',
      '[5_MAQ_1] Sought care by a general practitioner or clinic': 'true',
      '[5_MAQ_2] Sought care in a Emergency Department': 'true',
      '[257_SAQ] LongÂ COVID is having new or worsening symptoms for': 3,
      '[158_MAQ_27] I do not have any of these conditions': 'true',
      '[7_SAQ] Have you experienced shortness of breath in the pa': 1,
      '[160_SAQ] If you had COVID-19 was this symptom more frequent': 3,
      '[8_VAS] At its worst how breathless were you on a scale of': 6,
      '[163_MAQ_2] Exercising': 'true',
      '[163_MAQ_3] Everyday activities': 'true',
      '[338_FFT] At its worst in what other situation were you expe': 'test',
      '[162_VAS] Right now how breathless are you on a scale of 0-1': 1,
      '[161_MAQ_1] Walking': 'true',
      '[10_SAQ] Have you seen a health care provider about this sy': 1,
      '[11_SAQ] Were you satisfied with the plan of care prescribe': 2,
      '[24_SAQ] Have you experienced a lingering cough in the past': 1,
      '[164_SAQ] If you had COVID-19 was this symptom more frequent': 3,
      '[25_VAS] At its worst rate the severity of your cough on a ': 3,
      '[26_VAS] Right now rate the severity of your cough on a sca': 2,
      '[27_SAQ] Have you seen a health care provider about this sy': 1,
      '[28_SAQ] Were you satisfied with the plan of care prescribe': 1,
      '[31_SAQ] Have you experienced any pain or discomfort in you': 1,
      '[165_SAQ] If you had COVID-19 was this symptom more frequent': 3,
      '[32_VAS] At its worst how severe was the joint pain or disc': 5,
      '[33_VAS] Right now how severe is the joint pain or discomfo': 1,
      '[34_SAQ] Have you seen a health care provider about this sy': 1,
      '[35_SAQ] Were you satisfied with the plan of care prescribe': 2,
      '[38_SAQ] Have you experienced any pain or discomfort in you': 1,
      '[166_SAQ] If you had COVID-19 was this symptom more frequent': 2,
      '[39_VAS] At its worst how severe is any chest pain or disco': 4,
      '[40_VAS] Right now how severe is any chest pain or discomfo': 2,
      '[41_SAQ] Have you seen a health care provider about this sy': 1,
      '[42_SAQ] Were you satisfied with the plan of care prescribe': 2,
      '[45_SAQ] Have you experienced heart palpitations or feeling': 1,
      '[167_SAQ] If you had COVID-19 was this symptom more frequent': 3,
      '[46_VAS] At its worst how often were your heart palpitation': 6,
      '[47_VAS] Right now how often are your heart palpitations?(0': 2,
      '[48_SAQ] Have you seen a health care provider about this sy': 1,
      '[49_SAQ] Were you satisfied with the plan of care prescribe': 1,
      '[52_SAQ] Has a physician diagnosed you with myocarditis in ': 1,
      '[53_SAQ] Have you experienced depression in the past eighte': 1,
      '[168_SAQ] If you had COVID-19 was this symptom more frequent': 3,
      '[54_VAS] At its worst how severe was the depression you exp': 6,
      '[55_VAS] Right now how severe is the depression you are exp': 2,
      '[56_SAQ] Have you seen a health care provider about this sy': 1,
      '[57_SAQ] Were you satisfied with the plan of care prescribe': 1,
      '[60_SAQ] Have you experienced headaches in the past eightee': 1,
      '[169_SAQ] If you had COVID-19 was this symptom more frequent': 3,
      '[61_VAS] At its worst how severe were your headaches?(0 mea': 7,
      '[62_VAS] At its worst how often were your headaches?(0 mean': 3,
      '[63_VAS] Right now how severe are your headaches?(0 means m': 6,
      '[64_VAS] Right now how often are your headaches?(0 means ra': 3,
      '[65_SAQ] Have you seen a health care provider about this sy': 1,
      '[66_SAQ] Were you satisfied with the plan of care prescribe': 2,
      '[69_SAQ] Have you experienced fever which may come and go i': 1,
      '[170_SAQ] If you had COVID-19 was this symptom more frequent': 3,
      '[70_VAS] At its worst how severe were your fevers on a scal': 6,
      '[71_VAS] Right now how severe are your fevers on a scale of': 1,
      '[72_SAQ] Have you seen a health care provider about this sy': 1,
      '[73_SAQ] Were you satisfied with the plan of care prescribe': 2,
      '[76_SAQ] Did you have a Pulmonary Function (Breathing) Test': 1,
      '[77_SAQ] Were you told by a health care provider that you e': 1,
      '[89_SAQ] Have you experienced abnormal rash or skin irritat': 1,
      '[172_SAQ] If you had COVID-19 was this symptom more frequent': 3,
      '[90_VAS] At its worst how severe was your rashes or skin ir': 6,
      '[91_VAS] Right now how severe are your rashes or skin irrit': 2,
      '[92_SAQ] Have you seen a health care provider about this sy': 1,
      '[93_SAQ] Were you satisfied with the plan of care prescribe': 1,
      '[96_SAQ] Have you experienced hair loss in the past eightee': 1,
      '[173_SAQ] If you had COVID-19 was this symptom more frequent': 3,
      '[97_VAS] At its worst how severe was your hair loss on a sc': 6,
      '[98_SAQ] Right now do you continue to experience hair loss?': 2,
      '[99_SAQ] Have you seen a health care provider about this sy': 1,
      '[100_SAQ] Were you satisfied with the plan of care prescribe': 2,
      '[103_SAQ] Have you experienced prolonged loss of smell and/o': 1,
      '[174_SAQ] If you had COVID-19 was this symptom more frequent': 3,
      '[104_VAS] At its worst how severe was your loss of smell and': 6,
      '[105_VAS] Right now how severe is your loss of smell and/or ': 2,
      '[106_SAQ] Have you seen a health care provider about this sy': 1,
      '[107_SAQ] Were you satisfied with the plan of care prescribe': 2,
      '[110_SAQ] Have you experienced issues with your sleep or abi': 1,
      '[175_SAQ] If you had COVID-19 was this symptom more frequent': 3,
      '[111_VAS] At its worst how severely has your sleep been impa': 7,
      '[112_VAS] Right now how severely has your sleep been impacte': 1,
      '[113_SAQ] Have you seen a health care provider about this sy': 1,
      '[114_SAQ] Were you satisfied with the plan of care prescribe': 2,
      '[117_SAQ] Have you experienced issues with memory or concent': 1,
      '[176_SAQ] If you had COVID-19 was this symptom more frequent': 3,
      '[118_VAS] At its worst how severely has your memory and/or c': 7,
      '[119_VAS] Right now how severely has your memory and/or conc': 3,
      '[120_SAQ] Have you seen a health care provider about this sy': 2,
      '[124_SAQ] Brain fog refers to the feeling of being mentally ': 1,
      '[177_SAQ] If you had COVID-19 was this symptom more frequent': 3,
      '[125_VAS] At its worst how severe was your brain fog on a sc': 6,
      '[126_VAS] Right now how severe is your brain fog on a scale ': 2,
      '[127_SAQ] Have you seen a health care provider about this sy': 1,
      '[128_SAQ] Were you satisfied with the plan of care prescribe': 2,
      '[131_SAQ] Have you experienced anxiety in the past eighteen ': 1,
      '[178_SAQ] If you had COVID-19 was this symptom more frequent': 3,
      '[132_VAS] At its worst how severe was your anxiety on a scal': 6,
      '[133_VAS] Right now how severe is your anxiety on a scale of': 1,
      '[134_SAQ] Have you seen a health care provider about this sy': 1,
      '[135_SAQ] Were you satisfied with the plan of care prescribe': 1,
      '[138_SAQ] Have you experienced mood changes in the past eigh': 1,
      '[179_SAQ] If you had COVID-19 was this symptom more frequent': 2,
      '[139_VAS] At its worst how severe were your mood changes on ': 7,
      '[140_VAS] Right now how severe are your mood changes on a sc': 2,
      '[141_SAQ] Have you seen a health care provider about this in': 1,
      '[142_SAQ] Were you satisfied with the plan of care prescribe': 1,
      '[180_SAQ] Have you experienced fatigue in the past eighteen ': 1,
      '[181_SAQ] If you had COVID-19 was this symptom more frequent': 3,
      '[182_VAS] At its worst how severely did this affect your mob': 7,
      '[183_VAS] Right now how severely is your mobility activities': 2,
      '[184_SAQ] Have you seen a health care provider about this sy': 1,
      '[185_SAQ] Were you satisfied with the plan of care prescribe': 2,
      '[188_SAQ] Have you experienced a dead heavy feeling after st': 1,
      '[189_SAQ] If you had COVID-19 was this symptom more frequent': 2,
      '[190_VAS] At its worst how severely did this affect your mob': 7,
      '[191_VAS] Right now how severely is your mobility activities': 2,
      '[192_SAQ] Have you seen a health care provider about this sy': 1,
      '[193_SAQ] were you satisfied with the plan of care prescribe': 2,
      '[196_SAQ] Have you experienced a next-day soreness or fatigu': 1,
      '[197_SAQ] If you had COVID-19 was this symptom more frequent': 1,
      '[198_VAS] At its worst how severely did this affect your mob': 7,
      '[199_VAS] Right now how severely is your mobility activities': 2,
      '[200_SAQ] Have you seen a health care provider about this sy': 1,
      '[201_SAQ] Were you satisfied with the plan of care prescribe': 2,
      '[204_SAQ] Have you experienced mental fatigue after the slig': 1,
      '[205_SAQ] If you had COVID-19 was this symptom more frequent': 2,
      '[206_VAS] At its worst how severely did this affect your mob': 6,
      '[207_VAS] Right now how severely is your mobility activities': 2,
      '[208_SAQ] Have you seen a health care provider about this sy': 1,
      '[209_SAQ] Were you satisfied with the plan of care prescribe': 1,
      '[212_SAQ] Have you experienced physical tiredness after mini': 1,
      '[213_SAQ] If you had COVID-19 was this symptom more frequent': 2,
      '[214_VAS] At its worst how severely did this affect your mob': 6,
      '[215_VAS] Right now how severely is your mobility activities': 2,
      '[216_SAQ] Have you seen a health care provider about this sy': 1,
      '[217_SAQ] Were you satisfied with the plan of care prescribe': 2,
      '[220_SAQ] Have you experienced being physically tired or sic': 1,
      '[221_SAQ] If you had COVID-19 was this symptom more frequent': 3,
      '[222_VAS] At its worst how severely did this affect your mob': 6,
      '[223_VAS] Right now how severely is your mobility activities': 2,
      '[224_SAQ] Have you seen a health care provider about this sy': 1,
      '[225_SAQ] Were you satisfied with the plan of care prescribe': 1,
      '[228_SAQ] Have you had other symptoms that you believe were ': 1,
      '[231_FFT] What symptom did you experience?': 'vgv',
      '[230_SAQ] If you had COVID-19 was this symptom more frequent': 2,
      '[232_VAS] At its worst how severe was your symptom on a scal': 6,
      '[233_VAS] Right now how severe was your symptom on a scale o': 2,
      '[234_SAQ] Have you seen a health care provider about this sy': 1,
      '[235_SAQ] Were you satisfied with the plan of care prescribe': 2,
      '[313_SAQ] Have you had other symptoms that you believe were ': 1,
      '[314_FFT] What symptom did you experience?': 'test',
      '[315_SAQ] If you had COVID-19 was this symptom more frequent': 2,
      '[316_VAS] At its worst how severe was your symptom on a scal': 6,
      '[317_VAS] Right now how severe was your symptom on a scale o': 2,
      '[318_SAQ] Have you seen a health care provider about this sy': 1,
      '[319_SAQ] Were you satisfied with the plan of care prescribe': 2,
      '[324_SAQ] Have you had other symptoms that you believe were ': 1,
      '[325_FFT] What symptom did you experience?': 'beggsgsu',
      '[326_SAQ] If you had COVID-19 was this symptom more frequent': 2,
      '[327_VAS] At its worst how severe was your symptom on a scal': 6,
      '[328_VAS] Right now how severe was your symptom on a scale o': 2,
      '[329_SAQ] Have you seen a health care provider about this sy': 1,
      '[330_SAQ] Were you satisfied with the plan of care prescribe': 2,
      '[335_SAQ] Are there any other symptoms you have experienced ': 1,
      '[336_FFT] Please report the other symptoms you have had in t': 'gvv',
      '[246_SAQ] If you were to become exhausted after actively par': 2,
      '[247_SAQ] Do you experience a worsening of your fatigue/ener': 1,
      '[248_SAQ] Do you experience a worsening of your fatigue/ener': 1,
      '[249_SAQ] If you feel worse after activities how long does i': 7,
      '[250_SAQ] If you do not exercise is it because exercise make': 3,
      '[145_SAQ] How much are you currently affected in your everyd': 4,
      '[146_SAQ] Have you received a COVID-19 vaccine?': 1,
      '[251_CAL] What day did you receive your FIRST COVID vaccinat': 44533.74958333333,
      '[147_SAQ] Have you received a second dose of a COVID-19 vacc': 1,
      '[306_SAQ] Have you received a third dose booster of a COVID-': 3,
      '[252_SAQ] If you believe you had a COVID infection was your ': 2,
      '[312_SAQ] What was your sex at birth?': 1,
      '[148_SAQ] Do you identify as:': 2,
      '[149_NUM] What is your age?': 25,
      '[253_SAQ] What is your marital status?': 2,
      '[254_SAQ] What is the highest degree of level of education y': 4,
      '[255_SAQ] What is the levelÂ of your annual household income?': 7,
      '[150_FFT] Please enter the first 3 characters of your postal': 'T5P',
      '[153_SAQ] Do you wish to be contacted in the future regardin': 1,
      '[154_FFT] Because you have indicated yes to at least one of ': 'test',
      '[337_FFT] Because you have indicated yes to at least one of ':
        'test@mail.com',
      '[307_FFT] Do you have any additional information you would l': 'test',
    },
    {
      Name: 42176,
      'Device ID': '48E983DFD7FA4A3A9D4330CE622E8FAA',
      'Scheduled Time': '2022-11-21 13:33:19 MST',
      'Issued Time': '2022-11-21 13:33:19 MST',
      'Response Time': '2022-11-21 13:35:17 MST',
      'Duration (seconds) from scheduled to completion time': 118.636,
      'Duration (seconds) from first response to completion time': 74,
      Location: 'Unknown',
      '[156_SAQ] Have you had COVID-19? This can be medically confi': 2,
      '[1_SAQ] Were you confirmed positive for COVID-19 by either': 1,
      '[256_FFT] Please place your initials in the text box to conf': 'tv',
      '[2_SAQ] How long ago were you confirmed to have or suspect': 1,
      '[4_SAQ] How severe in your opinion was the disease within ': 1,
      '[157_MAQ_5] Never told that I experienced these things': 'true',
      '[5_MAQ_6] Did not seek medical care for my symptoms': 'true',
      '[257_SAQ] LongÂ COVID is having new or worsening symptoms for': 3,
      '[158_MAQ_27] I do not have any of these conditions': 'true',
      '[7_SAQ] Have you experienced shortness of breath in the pa': 2,
      '[24_SAQ] Have you experienced a lingering cough in the past': 2,
      '[31_SAQ] Have you experienced any pain or discomfort in you': 2,
      '[38_SAQ] Have you experienced any pain or discomfort in you': 2,
      '[45_SAQ] Have you experienced heart palpitations or feeling': 2,
      '[52_SAQ] Has a physician diagnosed you with myocarditis in ': 2,
      '[53_SAQ] Have you experienced depression in the past eighte': 2,
      '[60_SAQ] Have you experienced headaches in the past eightee': 2,
      '[69_SAQ] Have you experienced fever which may come and go i': 2,
      '[76_SAQ] Did you have a Pulmonary Function (Breathing) Test': 2,
      '[77_SAQ] Were you told by a health care provider that you e': 2,
      '[340_SAQ] Has a physician diagnosed you with a new thyroid c': 2,
      '[89_SAQ] Have you experienced abnormal rash or skin irritat': 2,
      '[96_SAQ] Have you experienced hair loss in the past eightee': 2,
      '[103_SAQ] Have you experienced prolonged loss of smell and/o': 2,
      '[110_SAQ] Have you experienced issues with your sleep or abi': 2,
      '[117_SAQ] Have you experienced issues with memory or concent': 2,
      '[124_SAQ] Brain fog refers to the feeling of being mentally ': 2,
      '[131_SAQ] Have you experienced anxiety in the past eighteen ': 2,
      '[138_SAQ] Have you experienced mood changes in the past eigh': 2,
      '[180_SAQ] Have you experienced fatigue in the past eighteen ': 2,
      '[188_SAQ] Have you experienced a dead heavy feeling after st': 2,
      '[196_SAQ] Have you experienced a next-day soreness or fatigu': 2,
      '[204_SAQ] Have you experienced mental fatigue after the slig': 2,
      '[212_SAQ] Have you experienced physical tiredness after mini': 2,
      '[220_SAQ] Have you experienced being physically tired or sic': 2,
      '[228_SAQ] Have you had other symptoms that you believe were ': 2,
      '[246_SAQ] If you were to become exhausted after actively par': 2,
      '[247_SAQ] Do you experience a worsening of your fatigue/ener': 2,
      '[248_SAQ] Do you experience a worsening of your fatigue/ener': 2,
      '[249_SAQ] If you feel worse after activities how long does i': 1,
      '[250_SAQ] If you do not exercise is it because exercise make': 3,
      '[145_SAQ] How much are you currently affected in your everyd': 1,
      '[358_SAQ] Do you take any prescription medications to treat ': 2,
      '[359_SAQ] Do you take any over-the-counter medications vitam': 2,
      '[360_SAQ] Are you doing anything else to help with your phys': 2,
      '[146_SAQ] Have you received a COVID-19 vaccine?': 2,
      '[312_SAQ] What was your sex at birth?': 1,
      '[148_SAQ] Do you identify as:': 2,
      '[149_NUM] What is your age?': 26,
      '[253_SAQ] What is your marital status?': 2,
      '[254_SAQ] What is the highest degree of level of education y': 3,
      '[255_SAQ] What is the levelÂ of your annual household income?': 1,
      '[153_SAQ] Do you wish to be contacted in the future regardin': 2,
      '[307_FFT] Do you have any additional information you would l': 'no',
    },
  ];

  return (
    <div>
      <DataTable data={dataArray} />
      <br />
      <CovidTable data={dataArray} />
      <br />
      <SymptomTable data={dataArray} />
    </div>
  );
}

export default Table;
