name: Get Closed Issues
on:
  # push:
  #   branches:
  #     - main
jobs:
  get-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get closed issues
        uses: actions/github-script@v5
        id: get_issues
        with:
          script: |
            const { data: issues } = await github.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'closed',
              per_page: 5
            });
            return issues.map(issue => issue.title);
      - name: Output issues to file
        run: echo '${{ steps.get_issues.outputs.result }}' > issues.txt