name: Notify Discord on PR Merge
on:
  # pull_request:
  #   types: [closed]
  push:
jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Discord
        uses: discord/discord-webhook@v1
        with:
          url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: 'testing discord ping'
          # content: 'PR #${{ github.event.pull_request.number }} has been merged!'